### ISSUE TITLE
Doesn't work in Catalina and keeps crashing and relaunching

### ISSUE THREAD

**Issue by gonced8** [DaFuqtor/MiddleClick-Catalina#3] opened 2019-10-11 12:59 UTC
Is there any way to get debug messages?

**Comment by DaFuqtor** [comment] 2019-10-11 13:52
Duplicate of #2. Briefly, just follow the steps listed in [this attention](//github.com/DaFuqtor/MiddleClick-Catalina#attention-make-sure-to) from README

**Closed by DaFuqtor** 2019-10-11 13:52 UTC
