### ISSUE TITLE
MiddleClick restarts every few seconds and does not work

### ISSUE THREAD

**Issue by cht87** [DaFuqtor/MiddleClick-Catalina#10] opened 2019-10-24 09:09 UTC
The software does not work anymore on macOS Catalina 10.15.

It restarts every few seconds.

Do you need more information about my system? 

I use a MacBook Pro Mid-2015 15".

**Comment by GameAndElse** [comment] 2019-10-24 11:46
Same Problem here.
Same Macbook Model
Same OS Version.
It lasts a few seconds up to a few minutes.

**Comment by Erik-White** [comment] 2019-10-24 12:12
I had the same issue. It is due to a previous version of Middleclick that you need to remove from your privacy settings. [From the author](https://github.com/DaFuqtor/MiddleClick-Catalina/issues/2#issuecomment-539954049):

> Now, as [the attention](//github.com/DaFuqtor/MiddleClick-Catalina#attention-make-sure-to) in README suggests, go to `System Preferences` > `Security & Privacy` > `Privacy` > `Accessibility`, then `Click the lock to make changes` and tick `MiddleClick` under `Allow the apps below to control your computer`.
> Thus, it'll work. And will stop restarting.
> 
> (It needs Accessibility control to interact with Trackpad and Mouse)

**Comment by DaFuqtor** [comment] 2019-10-24 12:15
Closed as a duplicate of #2

**Closed by DaFuqtor** 2019-10-24 12:15 UTC
Labels: duplicate
